/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import frames.panels.student_AddPanel;
import frames.panels.student_UpdatePanel;
import frames.panels.student_listpanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Toolkit;


/**
 *
 * @author abdelfattah
 */
public class admin_studentsframe extends javax.swing.JInternalFrame {

    /**
     * Creates new form admin_studentsframe
     */
    student_AddPanel p1;
    student_UpdatePanel p2;
    student_listpanel p3;
    GridBagLayout layout = new GridBagLayout();
    
    
    public admin_studentsframe() {
        initComponents();
        p1  = new student_AddPanel();
        p2  = new student_UpdatePanel();
        p3  = new student_listpanel();
        DynamicPanel.setLayout(layout);
        GridBagConstraints c =new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        
        DynamicPanel.add(p1, c);
        DynamicPanel.add(p2, c);
        DynamicPanel.add(p3, c);
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        
        //FULL SCREEN 
        //this.setUndecorated();
        Toolkit tk = Toolkit.getDefaultToolkit();
        double width = tk.getScreenSize().getWidth();
        double Height = tk.getScreenSize().getHeight();
        this.setSize((int)width, (int)Height);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1add = new javax.swing.JButton();
        jButton2list = new javax.swing.JButton();
        jButton3update = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jButton1add.setBackground(new java.awt.Color(0, 0, 0));
        jButton1add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1add.setForeground(new java.awt.Color(255, 255, 0));
        jButton1add.setText("Add Student");
        jButton1add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1addActionPerformed(evt);
            }
        });

        jButton2list.setBackground(new java.awt.Color(0, 0, 0));
        jButton2list.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2list.setForeground(new java.awt.Color(255, 255, 0));
        jButton2list.setText("Update Students");
        jButton2list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2listActionPerformed(evt);
            }
        });

        jButton3update.setBackground(new java.awt.Color(0, 0, 0));
        jButton3update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3update.setForeground(new java.awt.Color(255, 255, 0));
        jButton3update.setText("List Student");
        jButton3update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton1add, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jButton2list, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(jButton3update, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1addActionPerformed
        p1.setVisible(true);
          p2.setVisible(false);
            p3.setVisible(false);
    }//GEN-LAST:event_jButton1addActionPerformed

    private void jButton2listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2listActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
          p2.setVisible(true);
            p3.setVisible(false);
    }//GEN-LAST:event_jButton2listActionPerformed

    private void jButton3updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3updateActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
          p2.setVisible(false);
            p3.setVisible(true);
    }//GEN-LAST:event_jButton3updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton jButton1add;
    private javax.swing.JButton jButton2list;
    private javax.swing.JButton jButton3update;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
